development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://celtiaserver.herokuapp.com/faye"
  secret_token: "501ad5dd7eb0e70a9b5a154c8db7b38a22df7087ff895498539a774690403611"
  signature_expiration: 3600 # one hour
